### ISSUE TITLE
Get SAML2 Error code

### ISSUE THREAD

**Issue by frank-tenzing** [silverstripe/silverstripe-realme#31]
Hi there,

Is there any way we can get the SAML error code instead of the translated message from the service?

Thank you very much!

**Comment by robbieaverill** [comment]
Hi @frank-tenzing can you please provide the part of the code you're referring to?

**Comment by frank-tenzing** [comment]
Hi @robbieaverill, Thank you very much for the question.

I can see the error code is got in function `processSamlErrors` in `RealMeService` in code below https://github.com/silverstripe/silverstripe-realme/blob/master/src/RealMeService.php#L475:22.
```php
        if ($request->isPOST() && $request->postVar("SAMLResponse")) {
            $response = new OneLogin_Saml2_Response($this->getAuth()->getSettings(), $request->postVar("SAMLResponse"));
            $internalError = OneLogin_Saml2_Utils::query(
                $response->document,
                "/samlp:Response/samlp:Status/samlp:StatusCode/samlp:StatusCode/@Value"
            );
            if ($internalError instanceof DOMNodeList && $internalError->length > 0) {
                $internalErrorCode = $internalError->item(0)->textContent;
                $translatedMessage = $this->findErrorMessageForCode($internalErrorCode);
            }
        }
```
But outside of `RealMeService`, how can I get the status code and translate the code to customized messages instead of using pre-defined messages in `/silverstripe-realme/lang/en.yml`?

Cheers
Frank

**Comment by robbieaverill** [comment]
Ok I think there are three options we could look at pursuing:

1. Return structured information about the errors (note it doesn't look like the $errors var is used for much in that method), increase the method visibility to protected and allow user code (i.e. yours) to overload the class in order to define custom error handling after `parent::processSamlErrors($errors)`
2. Add extra log calls containing the $internalError and $internalErrorCode (won't help you catch it at runtime, but would help to debug retrospective issues)
3. Add an extension point i.e. `handleErrors($...)` and allow user code to do whatever they want with the error vars

Thoughts @frank-tenzing?

**Comment by madmatt** [comment]
Hey @frank-tenzing, do you think you still need this? I'll close this for now as it's been quite a while without any updates but let me know if you do.
